try {
    nonExistentFunction();
} catch(error) {
    console.error(error);
}